### PR TITLE
View and See All commands no longer display watched media by default

### LINKED ISSUE #59: Feature - Hide watched media
**Is your feature request related to a problem? Please describe.**
Seeing media that has already been watched in the watchlist might be annoying, as users will likely want to watch something new.

**Describe the solution you'd like**
Items with watched status are hidden from watchlists by default.

Requires #58 to be completed

### PR DESCRIPTION
**Pull request by tanagrams**
- Watched Media are hidden by default
- closes #59

### CODE REVIEW

**Review by jgai284 — CHANGES_REQUESTED** [review]
Great work, but the conflict needs to be solved. The watchlist JSON file can be made to empty

**Comment by xxu511** [comment]
The conflict fixed. LGTM

**Review by xxu511 — APPROVED** [review]
The conflict all fixed. Look good to me

**Review by jgai284 — APPROVED** [review]
lgtm

**Pull request merged**
